name: Sync upstream & comment out Clerk branding

on:
  schedule:
    - cron: "15 9 * * *"      # daily at 09:15 UTC; tweak as you like
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/clerk/clerk-ios.git
          git fetch upstream --prune

      - name: Detect upstream default branch
        id: branch
        run: |
          DEFAULT_BRANCH=$(git remote show upstream | sed -n '/HEAD branch/s/.*: //p')
          echo "branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

      - name: Preserve files before sync
        run: |
          echo "Preserving replacement script and workflow before syncing..."
          mkdir -p /tmp/scripts_backup
          cp scripts/replace_branding.sh /tmp/scripts_backup/ 2>/dev/null || echo "Script not found in current state"
          # Also backup our workflow file
          mkdir -p /tmp/workflows_backup
          cp .github/workflows/sync-and-replace.yml /tmp/workflows_backup/ 2>/dev/null || echo "Workflow file not found in current state"

      - name: Sync fork branch to upstream
        run: |
          git checkout -B "${{ steps.branch.outputs.branch }}"
          git reset --hard "upstream/${{ steps.branch.outputs.branch }}"

      - name: Remove upstream workflow files
        run: |
          echo "Removing upstream workflow files to prevent conflicts..."
          # Remove any workflow files that came from upstream (except our own)
          find .github/workflows -name "*.yml" -o -name "*.yaml" | grep -v "sync-and-replace" | xargs rm -f || true
          # Also remove any CI-related files that might conflict
          rm -f .github/workflows/ci.yml .github/workflows/CI.yml 2>/dev/null || true

      - name: Restore and run replacement script
        run: |
          echo "Current directory: $(pwd)"
          echo "Restoring replacement script..."

          # Create scripts directory and restore the script
          mkdir -p scripts
          if [ -f /tmp/scripts_backup/replace_branding.sh ]; then
            cp /tmp/scripts_backup/replace_branding.sh scripts/
            echo "Script restored successfully"
          else
            echo "Script backup not found, checking if it exists in upstream..."
            if [ -f scripts/replace_branding.sh ]; then
              echo "Script found in upstream"
            else
              echo "Error: Replacement script not found!"
              exit 1
            fi
          fi

          echo "Contents of scripts directory:"
          ls -la scripts/

          echo "Making sure script is executable..."
          chmod +x scripts/replace_branding.sh

          echo "Running replacement script..."
          bash scripts/replace_branding.sh

          echo "Checking for changes..."
          # Check if there are any changes at all
          if ! git diff --quiet; then
            echo "Changes detected, preparing selective commit..."
            # Reset any workflow files that came from upstream
            git checkout HEAD -- .github/workflows/ 2>/dev/null || true
            # Restore our workflow file from backup
            mkdir -p .github/workflows
            if [ -f /tmp/workflows_backup/sync-and-replace.yml ]; then
              cp /tmp/workflows_backup/sync-and-replace.yml .github/workflows/sync-and-replace.yml
              echo "Workflow file restored from backup"
            else
              echo "Warning: Workflow backup not found, workflow file may be missing"
            fi
            # Add all other changes
            git add .
            # Remove workflow files from staging (except our own)
            git reset HEAD .github/workflows/*.yml 2>/dev/null || true
            git reset HEAD .github/workflows/*.yaml 2>/dev/null || true
            # Add back our workflow file
            git add .github/workflows/sync-and-replace.yml
            # Commit if there are still changes
            if ! git diff --cached --quiet; then
              git commit -m "Comment out Clerk branding views"
              echo "Changes committed successfully."
            else
              echo "No changes to commit after workflow cleanup."
            fi
          else
            echo "No changes detected."
          fi

      # Optional build check — enable only if the package builds on Linux.
      # - name: (Optional) Swift build
      #   uses: swift-actions/setup-swift@v1
      #   with:
      #     swift-version: "5.9"
      #   # If it compiles on Linux:
      #   run: swift build -c release

      - name: Push changes
        run: |
          # Force-push ensures your fork stays exactly: upstream + your edits
          git push --force origin HEAD
